[server]
address = "127.0.0.1"
port = 8501
headless = true
maxUploadSize = 128
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#426379"
backgroundColor = "#f7f9fa"
secondaryBackgroundColor = "#edf1f3"
textColor = "#243746"
font = "sans serif"
