[server]
address = "127.0.0.1"
port = 8501
headless = true
maxUploadSize = 128
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#355F8A"
backgroundColor = "#F5F8FC"
secondaryBackgroundColor = "#EDF4FB"
textColor = "#172B43"
font = "sans serif"
